version: '3.7'
services:
  db:
    container_name: postgres
    image: postgres:16.4-bookworm
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - gorator

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    image: backend
    restart: on-failure
    environment:
      - GORATOR_DB_HOSTNAME=db
      - GORATOR_DB_PORT=5432
      - GORATOR_DB_USER=${POSTGRES_USER}
      - GORATOR_DB_PASSWORD=${POSTGRES_PASSWORD}
      - GORATOR_IS_DEBUG=1
      - GORATOR_DEBUG_USERS_PASSWORD=${GORATOR_DEBUG_USERS_PASSWORD}
      - GORATOR_ALLOWED_ORIGIN=http://localhost:5173
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - gorator

networks:
  gorator:
    name: gorator
    driver: bridge
