version: '3.7'
services:
  db:
    container_name: postgres
    image: postgres:16.4-bookworm
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - gorator

  init-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: init-backend
    image: dv4mp1r3/gorator-backend
    command: "./backend -s"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - gorator

  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: backend
    image: dv4mp1r3/gorator-backend
    restart: on-failure
    entrypoint: ["./backend"]
    env_file:
      - .env
    depends_on:
      - db
      - init-backend
    ports:
      - 8080:8080
    networks:
      - gorator

networks:
  gorator:
    name: gorator
    driver: bridge
