openapi: 3.1.3
info:
  title: wip
  description: wip
  version: 0.0.1
tags:
  - name: auth
    description: Authentication API
  - name: service
    description: Service API
  - name: entity
    description: Entity API (CRUD operations)
security:
  - cookieAuth: []
paths:
  '/user':
    post:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
    put:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/user/{id}':
    delete:
      tags: 
        - "entity"
      security:
        - cookieAuth: []
      responses:
        '204':
          description: success   
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []  
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailed'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/team':
    post:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
    put:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/team/{id}':
    delete:
      tags: 
        - "entity"
      security:
        - cookieAuth: []
      responses:
        '204':
          description: success   
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []  
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamDetailed'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/organization':
    post:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
    put:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/organization/{id}':
    delete:
      tags: 
        - "entity"
      security:
        - cookieAuth: []
      responses:
        '204':
          description: success   
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []  
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDetailed'                
        '400':
          description: Bad request
        '500':
          description: Internal server error 
  '/organizations':
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      parameters:
        - in: query
          name: name
          required: false
          schema: 
            $ref: '#/components/schemas/stringQueryParam'
        - in: query
          name: limit
          required: false
          schema: 
            $ref: '#/components/schemas/numberQueryParam'
        - in: query
          name: offset
          required: false
          schema: 
            $ref: '#/components/schemas/numberQueryParam'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationDetailed'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/teams':
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      parameters:
        - in: query
          name: name
          required: false
          schema: 
            $ref: '#/components/schemas/stringQueryParam'
        - in: query
          name: limit
          required: false
          schema: 
            $ref: '#/components/schemas/numberQueryParam'
        - in: query
          name: offset
          required: false
          schema: 
            $ref: '#/components/schemas/numberQueryParam'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamDetailed'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/users':
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      parameters:
        - in: query
          name: username
          required: false
          schema: 
            $ref: '#/components/schemas/stringQueryParam'
        - in: query
          name: email
          required: false
          schema: 
            $ref: '#/components/schemas/stringQueryParam'
        - in: query
          name: limit
          required: false
          schema: 
            $ref: '#/components/schemas/numberQueryParam'
        - in: query
          name: offset
          required: false
          schema: 
            $ref: '#/components/schemas/numberQueryParam'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDetailed'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/users/count':
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityCountResponse'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/organizations/count':
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityCountResponse'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/teams/count':
    get:
      tags:
        - "entity"
      security:
        - cookieAuth: []
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityCountResponse'                
        '400':
          description: Bad request
        '500':
          description: Internal server error
  '/login':
    post:
      tags:
        - "auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      security: []
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                    description: sessionId
                  user:
                    $ref: '#/components/schemas/UserDetailed'
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session=abcde12345; Path=/; HttpOnly
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
  schemas:
    stringQueryParam:
      type: string
      description: schema for string parameter in url
    numberQueryParam:
      type: number
      description: schema for number parameter in url
    EntityCountResponse:
      type: object
      properties:
        entity:
          type: string
        count:
          type: number
    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        avatar:
          type: string
        active:
          type: boolean
    UserDetailed:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        avatar:
          type: string
        active:
          type: boolean
        teams:
          type: array
          items:
            $ref: '#/components/schemas/Team'
        organizations:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
    Team:
      type: object
      properties:
        name:
          type: string
        avatar:
          type: string
        active:
          type: boolean
    TeamDetailed:
      type: object
      properties:
        name:
          type: string
        avatar:
          type: string
        active:
          type: boolean
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        organizations:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
    Organization:
      type: object
      properties:
        name:
          type: string
        avatar:
          type: string
        active:
          type: boolean
    OrganizationDetailed:
      type: object
      properties:
        name:
          type: string
        avatar:
          type: string
        active:
          type: boolean
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        teams:
          type: array
          items:
            $ref: '#/components/schemas/Team'